Adding a few additional features, such as colors, and possiblity to do cleanup in some cases (need to think when those cases would be

diff --git a/coinbrew b/coinbrew
--- a/coinbrew
+++ b/coinbrew
@@ -159,8 +159,7 @@ function parse_args {
                             ;;
                     esac
                 else
-                    echo "No path provided for --prefix"
-                    exit 3
+                    die "Error: ${RED}No path provided for --prefix${NOFORMAT}" 3
                 fi
                 ;;
             -b|--build-dir)
@@ -174,8 +173,7 @@ function parse_args {
                             ;;
                     esac
                 else
-                    echo "No path provided for --build-dir"
-                    exit 3
+                    die "Error: ${RED}No path provided for --build-dir${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -185,24 +183,22 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     jobs=$option_arg
                 else
-                    echo "No number specified for --parallel-jobs"
-                    exit 3
+                    die "Error: ${RED}No number specified for --parallel-jobs${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
                 fi
                 ;;
             --threads)
-                echo "The 'threads' argument has been re-named 'parallel-jobs'."
-                echo "Please re-run with correct argument name"
-                exit 3
+                msg "Error: ${RED}The 'threads' argument has been re-named 'parallel-jobs'."
+                msg "Please re-run with correct argument name"
+                die "${NOFORMAT}Exiting." 3
                 ;;
             -v|--verbosity)
                 if [ x"$option_arg" != x ]; then
                     verbosity=$option_arg
                 else
-                    echo "No verbosity specified for --verbosity"
-                    exit 3
+                    die "Error: ${RED}No verbosity specified for --verbosity${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -212,8 +208,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     main_proj=$option_arg
                 else
-                    echo "No main project specified for --main-proj."
-                    exit 3
+                    die "Error: ${RED}No main project specified for --main-proj.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -223,8 +218,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     main_proj_version=$option_arg
                 else
-                    echo "No main project version specified for --main-proj-version."
-                    exit 3
+                    die "Error: ${RED}No main project version specified for --main-proj-version.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -234,8 +228,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     main_proj_sha=$option_arg
                 else
-                    echo "No main project specified for --main-proj-sha."
-                    exit 3
+                    die "Error: ${RED}No main project specified for --main-proj-sha.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -245,8 +238,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     coin_skip_projects=$option_arg
                 else
-                    echo "No projects specified with --skip."
-                    exit 3
+                    die "Error: ${RED}No projects specified with --skip.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -256,8 +248,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     checkout_time=$option_arg
                 else
-                    echo "No checkout time specified with --time."
-                    exit 3
+                    die "No checkout time specified with --time.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -267,8 +258,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     run_tests=$option_arg
                 else
-                    echo "No argument specified with --tests."
-                    exit 3
+                    die "Error: ${RED}No argument specified with --tests.${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -279,8 +269,7 @@ function parse_args {
                     download_projs=$option_arg
                     download=true
                 else
-                    echo "No argument specified with --download-binary"
-                    exit 3
+                    die "Error: ${RED}No argument specified with --download-binary${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -290,8 +279,7 @@ function parse_args {
                 if [ x"$option_arg" != x ]; then
                     platform=$option_arg
                 else
-                    echo "No argument specified with --platform"
-                    exit 3
+                    die "Error: ${RED}No argument specified with --platform${NOFORMAT}" 3
                 fi
                 if [ $legacy_format = false ]; then
                     shift
@@ -316,7 +304,7 @@ function parse_args {
                 ;;
             -h|--help)
                 help
-                exit 0
+                die "" 0
                 ;;
             --test)
                 run_tests=main
@@ -838,7 +826,7 @@ function prompt_for_action {
             ;;
         4)
             help
-            exit 0
+            die "" 0
             ;;
     esac
 
@@ -1029,7 +1017,7 @@ function prompt_for_rebuild {
             reconfigure=true
             ;;
         4)
-            exit 0
+            die "Exiting." 0
     esac
 
 }
@@ -1295,10 +1283,8 @@ function invoke_make {
         $sudo $MAKE -j $jobs $@ > /dev/null 2>&1
         if [ $? -ne 0 ]; then
             $sudo $MAKE -j $jobs $@ > /dev/null
-            echo
-            echo "Build failed, see error output above"
-            echo
-            exit 1
+            msg ""
+            die "Error: ${RED}Build failed, see error output above${NOFORMAT}" 1
         fi
         set -e
     elif [ $v = 2 ]; then
@@ -1306,10 +1292,8 @@ function invoke_make {
         $sudo $MAKE -j $jobs $@ 2> /dev/null
         if [ $? -ne 0 ]; then
             $sudo $MAKE -j $jobs $@ > /dev/null
-            echo
-            echo "Build failed, see error output above"
-            echo
-            exit 1
+            msg ""
+            die "Error: ${RED}Build failed, see error output above${NOFORMAT}" 1
         fi
         set -e
     else
@@ -1349,25 +1333,24 @@ function build_proj {
             "$config_script" --disable-dependency-tracking --disable-option-checking \
                              --prefix=$prefix "${!configure_options[@]}" > /dev/null
             if [ $? -ne 0 ]; then
-                echo
-                echo "Configuration failed, re-running with output enabled"
-                echo
+                msg ""
+                msg "Configuration failed, re-running with output enabled"
+                meg ""
                 "$config_script" --disable-dependency-tracking --prefix=$prefix \
                                  "${!configure_options[@]}"
-                echo
-                echo "Here is the contents of config.log"
-                echo
+                msg ""
+                msg"Here is the contents of config.log"
+                msg ""
                 cat config.log
                 if [ "$(command -v pkg-config)" = "" ] &&
                        [ "$(command -v pkgconf)" = "" ]; then
-                    echo "No pkg-config or pkgconf were found on your system"
-                    echo "If packages were not found during configuration," 
-                    echo "this could be the reason."
-                    echo "Installation is highly recommended."
-                    echo "See https://coin-or.github.io for details"
-                    echo
+                    msg "${RED}No pkg-config or pkgconf were found on your system"
+                    msg "If packages were not found during configuration," 
+                    msg "this could be the reason."
+                    msg "Installation is highly recommended."
+                    msg "See https://coin-or.github.io for details${NOFORMAT}"
                 fi
-                exit 1
+                die "" 1
             fi
             set -e
         fi
@@ -1381,10 +1364,10 @@ function build_proj {
             $MAKE clean > /dev/null 2>&1
             if [ $? -ne 0 ]; then
                 $sudo $MAKE clean > /dev/null
-                echo
-                echo "Build failed, see error output above"
-                echo
-                exit 1
+                msg
+                msg "Error: ${RED}Build failed, see error output above"
+                msg
+                die "${NOFORMAT}" 1
             fi
             set -e
         fi
@@ -1558,6 +1541,47 @@ function get_cached_options {
 
 }
 
+###################################################################################
+# Some utility routines
+###################################################################################
+
+cleanup() {
+    trap - SIGINT SIGTERM ERR EXIT
+    # script cleanup here
+}
+
+setup_colors() {
+    if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+        NOFORMAT='\033[0m'
+        RED='\033[0;31m'
+        GREEN='\033[0;32m'
+        ORANGE='\033[0;33m'
+        BLUE='\033[0;34m'
+        PURPLE='\033[0;35m'
+        CYAN='\033[0;36m' YELLOW='\033[1;33m'
+    else
+        NOFORMAT=''
+        RED=''
+        GREEN=''
+        ORANGE=''
+        BLUE=''
+        PURPLE=''
+        CYAN=''
+        YELLOW=''
+    fi
+}
+
+msg() {
+    echo >&2 -e "${1-}"
+}
+
+die() {
+    local msg=$1
+    local code=${2-1} # default exit status 1
+    msg "$msg"
+    exit "$code"
+}
+
 ###########################################################################
 # Main script starts here
 ###########################################################################
@@ -1574,22 +1598,22 @@ echo
 ###################################################################################
 
 if [ $(echo ${BASH_VERSION} | cut -d "." -f 1) -le "3" ]; then
-    echo "This script requires bash version 4 or greater."
-    echo "You are probably on macOS, which comes with version 3."
-    echo "Please install a recent bash using homebrew (https://brew.sh)."
-    exit 100
+    msg "Error: ${RED}This script requires bash version 4 or greater."
+    msg "You are probably on macOS, which comes with version 3."
+    msg "Please install a recent bash using homebrew (https://brew.sh)."
+    die "${NOFORMAT}Exiting." 100
 fi
 
 if [ "$(command -v pkg-config)" = "" ] && [ "$(command -v pkgconf)" = "" ]; then
-    echo "No pkg-config or pkgconf found on system"
-    echo "If packages are not found during configuration," 
-    echo "this could be the reason. Installation is highly recommended."
-    echo "See https://coin-or.github.io for details"
-    echo
+    msg "${RED}No pkg-config or pkgconf found on system"
+    msg "If packages are not found during configuration," 
+    msg "this could be the reason. Installation is highly recommended."
+    msg "See https://coin-or.github.io for details"
+    msg "${NOFORMAT}"
 fi
 
 # Exit when command fails
-set -e
+set -Ee
 #Attempt to use undefined variable outputs error message, and forces an exit
 set -u
 #Causes a pipeline to return the exit status of the last command in the pipe
@@ -1599,6 +1623,11 @@ set -o pipefail
 #Take care of issues caused by other languages
 export LC_NUMERIC="en_US.UTF-8"
 export LANG="en_US.UTF-8"
+
+#Trap some signals
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
 
 # Set defaults
 root_dir=$PWD
@@ -1655,6 +1684,7 @@ fi
 # Parse the command-line arguments
 ###################################################################################
 
+setup_colors
 parse_args "$@"
 
 ###################################################################################
@@ -1680,10 +1710,10 @@ if [ $build = "true" ] || [ $install = "true" ] || [ $uninstall = "true" ]; then
     
     #Check whether build directory creation was successful
     if [ ! -d $build_dir ]; then
-        echo "Build directory cannot be created."
-        echo "Please create it and make it writable."
-        echo "Then re-run script"
-        exit 4
+        msg "Error: ${RED}Build directory cannot be created."
+        msg "Please create it and make it writable."
+        msg "Then re-run script"
+        die "${NOFORMAT}Exiting." 4
     fi
     echo "Package will be built in $build_dir"
     echo
@@ -1699,7 +1729,7 @@ if [ $num_actions = 0 ]; then
     else
         if [ $configure_help = false ]; then
             help
-            exit 0
+            die "" 0
         fi
     fi
 fi
@@ -1710,8 +1740,7 @@ fi
 
 if [ x"$prefix" != x ] && [ $build = "false" ] && [ $download = false ] &&
        [ $install = false ]; then
-    echo "Prefix should only be specified with build, download, or install commands"
-    exit 3
+    die "Error: ${RED}Prefix should only be specified with build, download, or install commands.${NOFORMAT}" 3
 fi
 
 if [ $download = "true" ] && [ $fetch = "false" ] && [ $build = "false" ] &&
@@ -1733,7 +1762,7 @@ if [ "$main_proj" = "" ]; then
         else
             echo "In non-interactive mode, main project must be specified."
         fi
-        exit 20
+        die "Exiting." 20
     fi
 fi
 
@@ -1824,8 +1853,7 @@ if [ $get_latest_release = "true" ] ; then
         fi
     else
 	echo
-	echo "It appears that $main_proj has no releases. You'll need to specify a branch as ${main_proj}:branch."
-	exit 31
+	die "Error: ${RED}It appears that $main_proj has no releases. You'll need to specify a branch as ${main_proj}:branch.${NOFORMAT}" 31
     fi
 fi
 
@@ -1901,8 +1929,7 @@ else
            echo "Fetching will be done automatically..."
            fetch=true
        else
-           echo "Please fetch before asking for help on configuration."
-           exit 30
+           die "Error: ${RED}Please fetch before asking for help on configuration.${NOFORMAT}" 30
        fi
     fi
 fi
@@ -2048,7 +2075,7 @@ if [ "$main_proj" != "" ]; then
         else
             echo "Can't find configure file for main project!"
         fi
-        exit 0
+        die "Exiting." 0
     fi
 fi
 
